### PR TITLE
Combat

### PR DESCRIPTION
**Pull request by WeaverofBrokenThreads**
It still has the fix to the recall soldiers fix, which I don't think is a good fix anyway. If people really wanted to abuse it, they could find a million different ways to do it. But right now it prevents legitimate players from fixing situations that never should have happened.

### CODE REVIEW

**Comment by tvogt** [comment]
merged to github, now I need to merge it with my local repository and put it online.

**Comment by tvogt** [comment]
@WeaverofBrokenThreads - I also need a Command script to update the changed data. The DataFixtures do NOT update existing data.

**Comment by WeaverofBrokenThreads** [comment]
Really? Aren't they just gonna do attacker->weapon in combat, and pull up the right stats? Otherwise, I am not sure how I can help you out with the command script.

**Comment by tvogt** [comment]
They will pull the numbers from the database. The DataFixture scripts are there to fill the database initially.

A script to update existing data would need to fetch the existing entity, update any changed variables, and then write it back. Can be a Symfony command, or an SQL script, both is fine with me.

**Comment by WeaverofBrokenThreads** [comment]
Sorry, I don't know how to do that.

**Comment by Zanaras** [comment]
Tom, at the minimum, we'd need to know the table structure in order to write an SQL script. Table names and column orders, at the very minimum.

I can infer a certain amount of the structure from how the forms interact with the QueryBuilder to generate the options they provide but a lot of the tables are enigmas to me layout wise.

As for a Command script, building one for each individual DataFixture would require the least work (though far more work than running SQL scripts) given that you can use the executeUpdate to pass information to it, but you'd have to work the updates into a separate file. If you wanted to standardize it, and didn't mind the extra time it'd take, you could have the same script run a query to check for a row's existence, then add it if it doesn't exist or skip it if it does. You could then use it to add any it didn't find, which should all be doable in a single script, courtesy of Doctrine DBAL.

SQL scripts sound as if they'd be more time-effective though. At least in the short term. Partially because I'm too tired to care at the moment, and partially because I'm not sure how M&F stores php arrays in it's database.

**Comment by tvogt** [comment]
Please don't make an SQL script.

Check the existing commands for example how to make a command script, it's really very simple. Then copy the code from the DataFixtures script and modify it so it only applies the new data.

To modify existing data, you first need to fetch the existing entity, there are hundreds of examples for this in the code, the easiest is something like `$spear = $em->getRepository('BM2Bundle:EquipmentType')->findOneByName('spear');`  and then change the settings you want to change, e.g. `$spear->setDamage(123);`

Don't forget $em->flush(); at the end. That is all, it really is easy. Don't do SQL. We have an ORM.

**Comment by Zanaras** [comment]
See post at http://forum.mightandfealty.com/index.php/topic,3767.msg30753.html#msg30753 please.

**Pull request merged**
